services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garage_manager
    ports:
      - "3307:3306"   # Port MySQL exposé sur le conteneur hôte
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"      # Rediriger le port 8080 vers 80 de Nginx
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge
